sensors:

  # -------------- Conveyor Breakbeam -------------- #
  breakbeam_0:
    type: break_beam
    pose:
      xyz: [-0.004795, 4.492549, 0.879306]
      rpy: [0, 0, -1.557900]

  # -------------- Shelf Breakbeams -------------- #
  # Right-most lane
  breakbeam_1:
    type: break_beam
    pose:
      xyz: [-10, -3.64, 0.1]
      rpy: [0, 0, -1.557900]

  breakbeam_2:
    type: break_beam
    pose:
      xyz: [-15.25, -3.64, 0.1]
      rpy: [0, 0, -1.557900] 
      
  # Mid-right lane
  breakbeam_3:
    type: break_beam
    pose:
      xyz: [-10, -2.4, 0.1]
      rpy: [0, 0, 1.557900]

  breakbeam_4:
    type: break_beam
    pose:
      xyz: [-15.25, -2.4, 0.1]
      rpy: [0, 0, 1.557900]

  # Mid-left lane
  breakbeam_5:
    type: break_beam
    pose:
      xyz: [-10, 2.4, 0.1]
      rpy: [0, 0, -1.557900]

  breakbeam_6:
    type: break_beam
    pose:
      xyz: [-15.25, 2.4, 0.1]
      rpy: [0, 0, -1.557900] 

  # Left-most lane
  breakbeam_7:
    type: break_beam
    pose:
      xyz: [-10, 3.66, 0.1]
      rpy: [0, 0, 1.557900]

  breakbeam_8:
    type: break_beam
    pose:
      xyz: [-15.25, 3.66, 0.1]
      rpy: [0, 0, 1.557900]

  # -------------- Logical Cameras -------------- #
  logical_camera_0:
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [5.064537, -1.794935, 1.653008]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [3.160776, -1.806997, 1.653007]
      rpy: [0, 'pi/2', 'pi/2']
    
  logical_camera_3: # over agv1
    type: logical_camera
    pose:
      xyz: [-0.000447, 6.582773, 1.789697]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_4: # over agv2
    type: logical_camera
    pose:
      xyz: [0.072608, -7.175601, 1.753955]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_5: # over conveyer belt
    type: logical_camera
    pose:
      xyz: [-0.017222, 3.202186, 1.868044]
      rpy: [-3.112917, 1.561484, -3.109819]

  logical_camera_6: # over shelf
    type: logical_camera
    pose:
      xyz: [-13.47, 0.000000, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_7: # over bin
    type: logical_camera
    pose:
      xyz: [2.961171, 1.698910, 1.820011]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_8: # over shelf
    type: logical_camera
    pose:
      xyz: [-13.47, -3.024268, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_9: # over shelf
    type: logical_camera
    pose:
      xyz: [-13.47, 3.006604, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_10: # over shelf back
    type: logical_camera
    pose:
      xyz: [5.1, -3.637, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_11: # over shelf
    type: logical_camera
    pose:
      xyz: [-15.52, -3.024268, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_12: # over shelf
    type: logical_camera
    pose:
      xyz: [-15.52, 3.006604, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_13: # over shelf back
    type: logical_camera
    pose:
      xyz: [3.05, 3.63, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_14: # over shelf back
    type: logical_camera
    pose:
      xyz: [3.05, -3.637, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_15: # over shelf back
    type: logical_camera
    pose:
      xyz: [5.1, 3.63, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_16: # over shelf back
    type: logical_camera
    pose:
      xyz: [-15.52, 0.000000, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']
