# RWA4
#drop parts: no
#new order: no
#flipped part: yes
#faulty parts: yes
#faulty gripper: no
#moving obstacles: yes (2: aisles 2 and 3)
#sensor blackout: yes

options:
  insert_models_over_bins: false
  insert_models_over_shelves: true
  belt_population_cycles: 0

#shelf_layout:
#  row_1: ['base','collar',0,'base'] #shelves: 3, 4, 5
#  row_2: ['pipe',0,'base','base']   #shelves: 6, 7, 8
#  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv2]
    products:
#      product_0:
#        type: gasket_part_green
#        pose:
#          xyz: [0.15, -0.2, 0]
#          rpy: [0, 0, 'pi/2']
#      product_1:
#        type: disk_part_blue
#        pose:
#          xyz: [-0.1, -0.2, 0]
#          rpy: [0, 0, 'pi/4']
      product_0:
        type: disk_part_blue
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 'pi/4']

models_over_bins:
  bin3:
    models:
      disk_part_blue:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi']
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      piston_rod_part_red:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin1:
    models:
      gasket_part_green:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3


#sensor_blackout:
#  product_count: 1
#  duration: 50

#faulty_products:
#  - pulley_part_blue_3
#  - piston_rod_part_red_2
#  - piston_rod_part_red_6
#  - gasket_part_green_4
faulty_products:
  - pulley_part_blue_1
  - pulley_part_blue_2
  - pulley_part_blue_3
  - piston_rod_part_red_2
  - piston_rod_part_red_1
  - piston_rod_part_red_3
  - gasket_part_green_9
  - gasket_part_green_1
  - gasket_part_green_2
  - gasket_part_green_4
  - disk_part_blue_1
  - disk_part_blue_2
  - disk_part_blue_3

time_limit: -1
