sensors:
  depth_camera_0:
    type: depth_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_0:
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [5.064537, -1.794935, 1.653008]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [3.160776, -1.806997, 1.653007]
      rpy: [0, 'pi/2', 'pi/2']

  breakbeam_0:
    type: break_beam
    pose:
      xyz: [-0.004795, 4.492549, 0.879306]
      rpy: [0, 0, -1.557900]
    
  logical_camera_3: # over agv1
    type: logical_camera
    pose:
      xyz: [-0.000447, 6.582773, 1.789697]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_4: # over agv2
    type: logical_camera
    pose:
      xyz: [0.072608, -7.175601, 1.753955]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_5: # over conveyer belt
    type: logical_camera
    pose:
      xyz: [-0.017222, 3.202186, 1.868044]
      rpy: [-3.112917, 1.561484, -3.109819]

  logical_camera_12: # over shelf
    type: logical_camera
    pose:
      xyz: [-14.074425, 0.000000, 2.490000]
      rpy: [0, 'pi/2', 'pi/2']
